http:
  listener: 
    host: "localhost"
    port: "9081"
    path: "/TravelOnTipcalls/{ServiceType}"
db:
  sql:
    host: "localhost"
    port: "3306"
    user: "root"
    password: "Chaitanya@333"
    database: "routes"
    
    